In [2]:
import numpy as np
print(np.__version__)

2.4.4


In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# Use a tuple to create a NumPy array:

import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

#### 0-D Arrays

In [5]:
import numpy as np
arr = np.array(42)
print(arr)

42


#### 1-D Arrays

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.



In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [8]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Check Number of Dimensions?

In [9]:
# Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Higher Dimensional Arrays

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

print('No of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
No of dimensions:  5
